CREATE TABLE IF NOT EXISTS Contactos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    autor INT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    contenido VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    updated_at DATETIME DEFAULT NULL ON UPDATE NOW(),
    deleted_at DATETIME DEFAULT NULL,
    FOREIGN KEY (autor) REFERENCES Autores(id) ON DELETE CASCADE
);
